[client]
	[client.visual_options]
		on_top=true
		distance=16
		horizontal_offset=0
		hide_waila=true
		tasks=true
		goals=true
		challenges=true
		title_color=4281541120
		name_color=4294967295
	[client.duration_options]
		task_effect_fadein=0.5
		task_effect_fadeout=1.5
		task_duration=7.0
		goal_effect_fadein=0.5
		goal_effect_fadeout=1.5
		goal_duration=7.0
		challenge_effect_fadein=1.25
		challenge_effect_fadeout=1.5
		challenge_duration=7.0
	[client.functionality_options]
		whitelist=[]
		mute_tasks=false
		mute_goals=false
		mute_challenges=false
