name = "Luminary"
author = "newtykins"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa198e4af7c3403fcafecf6577807044a6c168e35e2b9f43659908e3a7f77824"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.78"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
