name = "Luminary"
author = "newtykins"
version = "1.0.0-pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc36891ff6500a640829099fa7b6cc83ec15abd6c7817a5c0f4da08e43d2d708"

[versions]
minecraft = "1.19.3"
quilt = "0.18.3"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
